import eslint from '@eslint/js';
import boundaries from 'eslint-plugin-boundaries';

export default [
  eslint.configs.recommended,
  {
    plugins: {
      boundaries,
    },
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        console: 'readonly',
        window: 'readonly',
        document: 'readonly',
        localStorage: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        Promise: 'readonly',
        Map: 'readonly',
        Set: 'readonly',
        Array: 'readonly',
        Object: 'readonly',
        Date: 'readonly',
        Math: 'readonly',
        Number: 'readonly',
        String: 'readonly',
        Boolean: 'readonly',
        JSON: 'readonly',
        isNaN: 'readonly',
        isFinite: 'readonly',
        parseInt: 'readonly',
        parseFloat: 'readonly',
        process: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      'no-console': ['warn', { allow: ['debug', 'info', 'warn', 'error'] }],
      'no-implicit-globals': 'error',
      'no-implied-eval': 'error',
      'no-new-func': 'error',
      'no-new-wrappers': 'error',
      'no-proto': 'error',
      'no-script-url': 'error',
      'no-with': 'error',
      eqeqeq: ['error', 'always'],
      curly: ['error', 'all'],
      'default-case': 'error',
      'default-case-last': 'error',
      'no-empty-function': 'error',
      'no-var': 'error',
      'prefer-const': 'error',
      'object-shorthand': 'error',
      'quote-props': ['error', 'as-needed'],
      'array-callback-return': 'error',
      'consistent-return': 'error',
      'require-await': 'error',
      'no-return-await': 'error',
      yoda: 'error',
      'no-delete-var': 'error',
      'no-undef': 'error',
      'no-use-before-define': ['error', { functions: false, classes: true, variables: true }],
      complexity: ['error', { max: 10 }],
      'max-lines': ['error', { max: 600 }],
      'boundaries/element-types': 'error',
    },
    settings: {
      boundaries: {
        elements: ['src/**'],
      },
    },
  },
];
